### ISSUE TITLE
sync?

### ISSUE THREAD

**Issue by jbeker** [caseymrm/drivesink#14]
I'm a bit confused, your documentation says to use the command `sync` but there is no `sync` command? All I see is `upload` and `download`? And if I try to `upload` a second time I can't because the files already exist?

Am I missing something?

**Comment by RFKDOT** [comment]
I 'm in the same situation as you , you found a way to fix it or some alternative , basically intend to make backups of my photos in cloudrive .

**Comment by jbeker** [comment]
Nope. I switched to using [duplicity](http://duplicity.nongnu.org)
