### ISSUE TITLE
NAME_ALREADY_EXISTS

### ISSUE THREAD

**Issue by Gnowknayme** [caseymrm/drivesink#24]
I started using drivesink to upload my photos to Amazon, and kept getting NAME_ALREADY_EXISTS errors when continuing my upload. I've verified that the files are in fact on my Amazon Cloud Drive, and it looks like drivesink should skip them, but here's the error:

`INFO       drivesink:36 upload_child_file Uploading /media/pictures/Nikon/2010-06/DSC_5975.JPG to 2010-06
INFO       connectionpool:696 _new_conn Starting new HTTPS connection (1): content-na.drive.amazonaws.com
DEBUG      connectionpool:375 _make_request Setting read timeout to None
DEBUG      connectionpool:415 _make_request "POST /cdproxy/nodes HTTP/1.1" 409 261
ERROR      drivesink:256 _request Got Amazon code NAME_ALREADY_EXISTS: Node with the name dsc_5975.jpg already exists under parentId xxxxxxxxxxxxxx conflicting NodeId: xxxxxxxxxxxx`

I managed to work around this by modifying drivesink to not exit when it gets this error, but it still uses a ton of wasted bandwidth because it's re-uploading files that have already been uploaded. I dug into this a bit more, and it looks like CloudNode.children() only gets 200 children at a time. So in folders where there are more than 200 files, it will not have the rest of the files, so it tries to re-upload. I'm not sure what the fix is here, but that's the cause.

**Comment by caseymrm** [comment]
Thanks for the report and debugging, @Gnowknayme .

That children() code needs to implement pagination: https://developer.amazon.com/public/apis/experience/cloud-drive/content/nodes#Pagination

I'm not actively using drivesink, so I'm not sure when I'll get to it, but if you'd like to take a shot, you would take the nodes variable here: https://github.com/caseymrm/drivesink/blob/master/drivesink.py#L23 and if ```nodes["nextToken"] ``` exists, you would make the same ```request_metadata``` request but add ```"?nextToken="+nodes["nextToken"]``` to the end, and repeat until there is no nextToken.

For extra credit ```children()``` should really be an iterator so the nextToken is only fetched when needed, but currently we always iterate through everything.

**Comment by Gnowknayme** [comment]
Unfortunately, I have zero experience with Python, so while I was able to hack my way around debugging, adding these changes is beyond my capabilities. I'll just continue letting mine do duplicate uploads until someone else can get around to making the changes.

For anyone else running into this, if you would like for your copy to keep uploading after getting a NAME_ALREADY_EXISTS error, just comment out lines 257 and 260 so that they look like this:
`
                #sys.exit(1)
            except Exception:
                pass
        #req.raise_for_status()
`

**Comment by Sciruss** [comment]
Ferran Munoz has implemented Pagination as well as error 500 retries here, resolving two issues: https://github.com/ferranmunoz/drivesink/commit/3901f598555194976080e4a4f172be91038632aa

**Comment by caseymrm** [comment]
Thanks for the pointer, merged in #25
