### ISSUE TITLE
Made this work woth Pyton 3.5

### ISSUE THREAD

**Issue by jensstutte** [caseymrm/drivesink#26]
[drivesink_python3_5.zip](https://github.com/caseymrm/drivesink/files/1691696/drivesink_python3_5.zip)
Dear all, I had quite some fiddling to make this work with Python 3.5. I attach my changes here. 

Changes:
- Made it work with Pyton 3.5
- Added graceful handling for duplicate errors
- Added filter for photos only (based on extensions) 
WARNING: the upload here is limeted to jpg/png, as this suits my needs. See the upload function to remove this.

**Comment by caseymrm** [comment]
Thanks @jensstutte and @dasos !
